name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up JDK 21 (Temurin)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Make Maven Wrapper Executable
        run: chmod +x mvnw

      - name: Build with Maven Wrapper
        run: ./mvnw clean install

      - name: Extract Version from pom.xml
        id: extract_version
        run: |
          VERSION=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_DAI_DEPLOY }}
        with:
          tag_name: v${{ env.VERSION }}
          release_name: Release v${{ env.VERSION }}
          draft: false
          prerelease: false

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: DAI-LAB-02
          path: target/DAI-LAB-02-1.0-SNAPSHOT.jar

      - name: Attach Artifact to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_DAI_DEPLOY }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/DAI-LAB-02-1.0-SNAPSHOT.jar
          asset_name: DAI-LAB-02-1.0-SNAPSHOT.jar
          asset_content_type: application/java-archive
