name: Build and Publish JAR to GitHub Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      # Étape 1 : Checkout du code
      - uses: actions/checkout@v4.0.0

      # Étape 2 : Configuration de Java 21
      - uses: actions/setup-java@v4.0.0
        with:
          java-version: "21"
          distribution: "temurin"

      # Étape 3 : Compilation du projet et génération du fichier JAR
      - name: Build with Maven
        run: ./mvnw clean package

      # Étape 4 : Création d'une release GitHub et upload du JAR dans la release
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_DAI_DEPLOY }}
        with:
          tag_name: 'v1.0.${{ github.run_number }}'  # Tag version dynamique
          release_name: 'Release v1.0.${{ github.run_number }}'
          draft: false
          prerelease: false

      # Étape 6 : Upload du JAR généré dans la release
      - name: Upload JAR to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/*.jar
          asset_name: DAI-LAB-02.jar
          asset_content_type: application/java-archive
